// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using prova_AnaliseProjeto.Models;

#nullable disable

namespace prova_AnaliseProjeto.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221207171347_NewModels")]
    partial class NewModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("prova_AnaliseProjeto.Models.Consumidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Consumidor");
                });

            modelBuilder.Entity("prova_AnaliseProjeto.Models.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Valor")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Pagamento");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Pagamento");
                });

            modelBuilder.Entity("prova_AnaliseProjeto.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsumidorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("PagamentoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConsumidorId");

                    b.HasIndex("PagamentoId")
                        .IsUnique();

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("prova_AnaliseProjeto.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<string>("descricao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("prova_AnaliseProjeto.Models.Boleto", b =>
                {
                    b.HasBaseType("prova_AnaliseProjeto.Models.Pagamento");

                    b.Property<string>("cod_de_barra")
                        .HasColumnType("text");

                    b.Property<DateTime>("data_de_vencimento")
                        .HasColumnType("timestamp without time zone");

                    b.HasDiscriminator().HasValue("Boleto");
                });

            modelBuilder.Entity("prova_AnaliseProjeto.Models.CartaoDeCredito", b =>
                {
                    b.HasBaseType("prova_AnaliseProjeto.Models.Pagamento");

                    b.Property<string>("numero")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("CartaoDeCredito");
                });

            modelBuilder.Entity("prova_AnaliseProjeto.Models.Pedido", b =>
                {
                    b.HasOne("prova_AnaliseProjeto.Models.Consumidor", "Consumidor")
                        .WithMany("Pedido")
                        .HasForeignKey("ConsumidorId");

                    b.HasOne("prova_AnaliseProjeto.Models.Pagamento", "Pagamento")
                        .WithOne("Pedido")
                        .HasForeignKey("prova_AnaliseProjeto.Models.Pedido", "PagamentoId");

                    b.Navigation("Consumidor");

                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("prova_AnaliseProjeto.Models.Produto", b =>
                {
                    b.HasOne("prova_AnaliseProjeto.Models.Pedido", null)
                        .WithMany("items")
                        .HasForeignKey("PedidoId");
                });

            modelBuilder.Entity("prova_AnaliseProjeto.Models.Consumidor", b =>
                {
                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("prova_AnaliseProjeto.Models.Pagamento", b =>
                {
                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("prova_AnaliseProjeto.Models.Pedido", b =>
                {
                    b.Navigation("items");
                });
#pragma warning restore 612, 618
        }
    }
}
